In [ ]:
joa = '/content/drive/MyDrive/che.csv'

In [ ]:
import pandas as pd

In [ ]:
joa = pd.read_csv(joa)

In [ ]:
joa.head()

Unnamed: 0  age  experience  current_job_years  current_house_years  \
0           0   23           3                  3                   13   
1           1   40          10                  9                   13   
2           2   66           4                  4                   10   
3           3   41           2                  2                   12   
4           4   47          11                  3                   14   

   married_single  house_ownership_rented  car_ownership_no  \
0               1                       1                 1   
1               1                       1                 1   
2               0                       1                 1   
3               1                       1                 0   
4               1                       1                 1   

   profession_Mechanical_engineer  profession_Software_Developer  ...  \
0                               1                              0  ...   
1                               0                              1  ...   
2                               0                              0  ...   
3                               0                              1  ...   
4                               0                              0  ...   

   profession_Statistician  profession_Web_designer  profession_Consultant  \
0                        0                        0                      0   
1                        0                        0                      0   
2                        0                        0                      0   
3                        0                        0                      0   
4                        0                        0                      0   

   profession_Chef  profession_Army_officer  profession_Surgeon  \
0                0                        0                   0   
1                0                        0                   0   
2                0                        0                   0   
3                0                        0                   0   
4                0                        0                   0   

   profession_Scientist  profession_Civil_engineer  \
0                     0                          0   
1                     0                          0   
2                     0                          0   
3                     0                          0   
4                     0                          0   

   profession_Industrial_Engineer  risk_flag  
0                               0          0  
1                               0          0  
2                               0          0  
3                               0          1  
4                               0          1  

[5 rows x 59 columns]

In [ ]:
joa = joa.iloc[:,1:]

In [ ]:
joa.head()

age  experience  current_job_years  current_house_years  married_single  \
0   23           3                  3                   13               1   
1   40          10                  9                   13               1   
2   66           4                  4                   10               0   
3   41           2                  2                   12               1   
4   47          11                  3                   14               1   

   house_ownership_rented  car_ownership_no  profession_Mechanical_engineer  \
0                       1                 1                               1   
1                       1                 1                               0   
2                       1                 1                               0   
3                       1                 0                               0   
4                       1                 1                               0   

   profession_Software_Developer  profession_Technical_writer  ...  \
0                              0                            0  ...   
1                              1                            0  ...   
2                              0                            1  ...   
3                              1                            0  ...   
4                              0                            0  ...   

   profession_Statistician  profession_Web_designer  profession_Consultant  \
0                        0                        0                      0   
1                        0                        0                      0   
2                        0                        0                      0   
3                        0                        0                      0   
4                        0                        0                      0   

   profession_Chef  profession_Army_officer  profession_Surgeon  \
0                0                        0                   0   
1                0                        0                   0   
2                0                        0                   0   
3                0                        0                   0   
4                0                        0                   0   

   profession_Scientist  profession_Civil_engineer  \
0                     0                          0   
1                     0                          0   
2                     0                          0   
3                     0                          0   
4                     0                          0   

   profession_Industrial_Engineer  risk_flag  
0                               0          0  
1                               0          0  
2                               0          0  
3                               0          1  
4                               0          1  

[5 rows x 58 columns]

In [ ]:
ro = joa.iloc[:,-1]

In [ ]:
ro.head()

0    0
1    0
2    0
3    1
4    1
Name: risk_flag, dtype: int64

In [ ]:
!pip install seaborn

In [ ]:
import seaborn as sns

In [ ]:
sns.heatmap(joa, annot=True, cmap='coolwarm')

In [ ]:
X = joa
y = ro

In [ ]:
X.describe()

age     experience  current_job_years  current_house_years  \
count  252000.000000  252000.000000      252000.000000        252000.000000   
mean       49.954071      10.084437           6.333877            11.997794   
std        17.063863       6.002590           3.647053             1.399037   
min        21.000000       0.000000           0.000000            10.000000   
25%        35.000000       5.000000           3.000000            11.000000   
50%        50.000000      10.000000           6.000000            12.000000   
75%        65.000000      15.000000           9.000000            13.000000   
max        79.000000      20.000000          14.000000            14.000000   

       married_single  house_ownership_rented  car_ownership_no  \
count   252000.000000           252000.000000     252000.000000   
mean         0.897905                0.920230          0.698413   
std          0.302774                0.270937          0.458948   
min          0.000000                0.000000          0.000000   
25%          1.000000                1.000000          0.000000   
50%          1.000000                1.000000          1.000000   
75%          1.000000                1.000000          1.000000   
max          1.000000                1.000000          1.000000   

       profession_Mechanical_engineer  profession_Software_Developer  \
count                   252000.000000                  252000.000000   
mean                         0.020702                       0.020052   
std                          0.142386                       0.140177   
min                          0.000000                       0.000000   
25%                          0.000000                       0.000000   
50%                          0.000000                       0.000000   
75%                          0.000000                       0.000000   
max                          1.000000                       1.000000   

       profession_Technical_writer  ...  profession_Statistician  \
count                252000.000000  ...             252000.00000   
mean                      0.020615  ...                  0.02304   
std                       0.142092  ...                  0.15003   
min                       0.000000  ...                  0.00000   
25%                       0.000000  ...                  0.00000   
50%                       0.000000  ...                  0.00000   
75%                       0.000000  ...                  0.00000   
max                       1.000000  ...                  1.00000   

       profession_Web_designer  profession_Consultant  profession_Chef  \
count            252000.000000          252000.000000    252000.000000   
mean                  0.021417               0.019079         0.018393   
std                   0.144769               0.136804         0.134368   
min                   0.000000               0.000000         0.000000   
25%                   0.000000               0.000000         0.000000   
50%                   0.000000               0.000000         0.000000   
75%                   0.000000               0.000000         0.000000   
max                   1.000000               1.000000         1.000000   

       profession_Army_officer  profession_Surgeon  profession_Scientist  \
count            252000.000000       252000.000000         252000.000000   
mean                  0.018496            0.018937              0.018972   
std                   0.134737            0.136301              0.136427   
min                   0.000000            0.000000              0.000000   
25%                   0.000000            0.000000              0.000000   
50%                   0.000000            0.000000              0.000000   
75%                   0.000000            0.000000              0.000000   
max                   1.000000            1.000000              1.000000   

       profession_Civil_engineer  profession_Industrial_Engineer  \
count              

In [ ]:
!pip install imbalanced-learn

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
X.drop('risk_flag',axis=1,inplace=True)

In [ ]:
sm = SMOTE(
    sampling_strategy='auto',  # samples only the minority class
    random_state=0,  # for reproducibility
    k_neighbors=5
)

X_sm, y_sm = sm.fit_resample(X, y)

In [ ]:
X_sm.describe()

age     experience  current_job_years  current_house_years  \
count  442008.000000  442008.000000      442008.000000        442008.000000   
mean       49.536058       9.815757           6.240371            11.970706   
std        17.203574       6.027663           3.684532             1.395788   
min        21.000000       0.000000           0.000000            10.000000   
25%        34.000000       5.000000           3.000000            11.000000   
50%        49.000000      10.000000           6.000000            12.000000   
75%        64.000000      15.000000           9.000000            13.000000   
max        79.000000      20.000000          14.000000            14.000000   

       married_single  house_ownership_rented  car_ownership_no  \
count   442008.000000           442008.000000     442008.000000   
mean         0.901181                0.925271          0.699976   
std          0.298420                0.262955          0.458269   
min          0.000000                0.000000          0.000000   
25%          1.000000                1.000000          0.000000   
50%          1.000000                1.000000          1.000000   
75%          1.000000                1.000000          1.000000   
max          1.000000                1.000000          1.000000   

       profession_Mechanical_engineer  profession_Software_Developer  \
count                   442008.000000                  442008.000000   
mean                         0.018199                       0.019685   
std                          0.133670                       0.138916   
min                          0.000000                       0.000000   
25%                          0.000000                       0.000000   
50%                          0.000000                       0.000000   
75%                          0.000000                       0.000000   
max                          1.000000                       1.000000   

       profession_Technical_writer  ...  profession_Drafter  \
count                442008.000000  ...       442008.000000   
mean                      0.019423  ...            0.018565   
std                       0.138006  ...            0.134984   
min                       0.000000  ...            0.000000   
25%                       0.000000  ...            0.000000   
50%                       0.000000  ...            0.000000   
75%                       0.000000  ...            0.000000   
max                       1.000000  ...            1.000000   

       profession_Statistician  profession_Web_designer  \
count            442008.000000            442008.000000   
mean                  0.020986                 0.018760   
std                   0.143338                 0.135676   
min                   0.000000                 0.000000   
25%                   0.000000                 0.000000   
50%                   0.000000                 0.000000   
75%                   0.000000                 0.000000   
max                   1.000000                 1.000000   

       profession_Consultant  profession_Chef  profession_Army_officer  \
count          442008.000000    442008.000000            442008.000000   
mean                0.017282         0.016285                 0.018430   
std                 0.130322         0.126569                 0.134499   
min                 0.000000         0.000000                 0.000000   
25%                 0.000000         0.000000                 0.000000   
50%                 0.000000         0.000000                 0.000000   
75%                 0.000000         0.000000                 0.000000   
max                 1.000000         1.000000                 1.000000   

       profession_Surgeon  profession_Scientist  profession_Civil_engineer  \
count       442008.000000         442008.000000              442008.000000   
mean             0.016893              0.018832                   0.017420   
std              0.128872              0.135932    

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
X = X_sm
y = y_sm

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=52)

In [ ]:
from sklearn.feature_selection import mutual_info_regression,mutual_info_classif
mi=mutual_info_classif(X_train,y_train)
mi=pd.Series(mi)
mi.index=X.columns
lol=mi.sort_values(ascending=False)
from sklearn.feature_selection import SelectPercentile
sel=SelectPercentile(mutual_info_classif,percentile=30).fit(X_train,y_train)
X.columns[sel.get_support()]

Index(['age', 'experience', 'current_job_years', 'current_house_years',
       'married_single', 'house_ownership_rented', 'car_ownership_no',
       'profession_Software_Developer', 'profession_Architect',
       'profession_Designer', 'profession_Financial_Analyst',
       'profession_Air_traffic_controller', 'profession_Politician',
       'profession_Chemical_engineer', 'profession_Dentist',
       'profession_Petroleum_Engineer', 'profession_Consultant'],
      dtype='object')

In [ ]:
X = X[['age', 'experience', 'current_job_years', 'current_house_years',
       'married_single', 'house_ownership_rented', 'car_ownership_no',
       'profession_Software_Developer', 'profession_Architect',
       'profession_Designer', 'profession_Financial_Analyst',
       'profession_Air_traffic_controller', 'profession_Politician',
       'profession_Chemical_engineer', 'profession_Dentist',
       'profession_Petroleum_Engineer', 'profession_Consultant']]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=52)

In [ ]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris

# Define the hyperparameter grid to search over
param_grid = {
    'n_estimators': np.arange(50, 300, 50),           # Number of trees in the forest
    'max_depth': [None] + list(np.arange(10, 50, 10)),  # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],                # Minimum samples required to split a node
    'min_samples_leaf': [1, 2, 4],                 # Minimum samples required at each leaf node
    'bootstrap': [True, False],                    # Whether to bootstrap samples when building trees
}

# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)

# Create RandomizedSearchCV object
random_search = RandomizedSearchCV(
    rf_classifier, param_distributions=param_grid, n_iter=20,
    scoring='accuracy', cv=3, n_jobs=-1, random_state=42
)

# Perform the hyperparameter search
random_search.fit(X_train, y_train)

# Print the best hyperparameters found
print("Best Hyperparameters:", random_search.best_params_)

# Evaluate the best model on the test data
best_rf_model = random_search.best_estimator_
test_accuracy = best_rf_model.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.2f}")

Best Hyperparameters: {'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_depth': None, 'bootstrap': False}
Test Accuracy: 0.91


In [ ]:
from sklearn.metrics import accuracy_score, roc_auc_score,confusion_matrix

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
sv=RandomForestClassifier(n_estimators=100, min_samples_split=5, min_samples_leaf=1, max_depth=None, bootstrap=False)

In [ ]:
sv.fit(X_train,y_train)
rf1=sv.predict(X_train)
accuracy_score(rf1,y_train)

0.9344386806935893

In [ ]:
roc_auc_score(rf1,y_train)

0.9382747958194492

In [ ]:
confusion_matrix(rf1,y_train)

array([[137486,   2861],
       [ 17424, 151634]])

In [ ]:
rf2=sv.predict(X_test)
accuracy_score(rf2,y_test)

0.9138631855991192

In [ ]:
roc_auc_score(rf2,y_test)

0.9178972501848752

In [ ]:
confusion_matrix(rf2,y_test)

array([[57167,  2495],
       [ 8927, 64014]])

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.preprocessing import MinMaxScaler
m=MinMaxScaler()
o=m.fit_transform(X_train)
l=m.transform(X_test)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
r=model.predict(X_train)
accuracy_score(r,y_train)

0.5416945427514099

In [ ]:
roc_auc_score(r,y_train)

0.5421569569639142

In [ ]:
confusion_matrix(r,y_train)

array([[76396, 63288],
       [78514, 91207]])

In [ ]:
rf2=model.predict(X_test)
accuracy_score(rf2,y_test)

0.5433134996945771

In [ ]:
roc_auc_score(rf2,y_test)

0.5435572231493853

In [ ]:
confusion_matrix(rf2,y_test)

array([[32773, 27237],
       [33321, 39272]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dr = DecisionTreeClassifier(splitter='best', min_samples_split=2, min_samples_leaf=1, max_features= None, max_depth=40, criterion= 'gini')

In [ ]:
dr.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=40)

In [ ]:
d=dr.predict(X_train)
accuracy_score(d,y_train)

0.9344451447132399

In [ ]:
roc_auc_score(d,y_train)

0.938156185729376

In [ ]:
confusion_matrix(d,y_train)

array([[137605,   2978],
       [ 17305, 151517]])

In [ ]:
rf2=dr.predict(X_test)
accuracy_score(rf2,y_test)

0.9101981101483375

In [ ]:
roc_auc_score(rf2,y_test)

0.9148963084159072

In [ ]:
confusion_matrix(rf2,y_test)

array([[56653,  2467],
       [ 9441, 64042]])

In [ ]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris



# Define the hyperparameter grid to search over
param_grid = {
    'criterion': ['gini', 'entropy'],              # Split criterion
    'splitter': ['best', 'random'],               # Split strategy
    'max_depth': [None] + list(np.arange(10, 110, 10)),  # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],             # Minimum samples required to split a node
    'min_samples_leaf': [1, 2, 4],              # Minimum samples required at each leaf node
    'max_features': ['auto', 'sqrt', 'log2', None],  # Number of features to consider for best split
}

# Create a Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Create RandomizedSearchCV object
random_search = RandomizedSearchCV(
    dt_classifier, param_distributions=param_grid, n_iter=30,
    scoring='accuracy', cv=3, n_jobs=-1, random_state=42
)

# Perform the hyperparameter search
random_search.fit(X_train, y_train)

# Print the best hyperparameters found
print("Best Hyperparameters:", random_search.best_params_)

# Evaluate the best model on the test data
best_dt_model = random_search.best_estimator_
test_accuracy = best_dt_model.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.2f}")


Best Hyperparameters: {'splitter': 'best', 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': None, 'max_depth': 40, 'criterion': 'gini'}
Test Accuracy: 0.91


In [ ]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

# Define the hyperparameter grid to search over
param_grid = {
    'C': np.logspace(-3, 3, 100),          # Inverse of regularization strength
    'penalty': ['l1', 'l2'],               # Regularization type (L1 or L2)
    'solver': ['liblinear', 'saga'],       # Solver for optimization
    'max_iter': np.arange(100, 1000, 100)  # Maximum number of iterations
}

# Create a Logistic Regression Classifier
lr_classifier = LogisticRegression(random_state=42)

# Create RandomizedSearchCV object
random_search = RandomizedSearchCV(
    lr_classifier, param_distributions=param_grid, n_iter=30,
    scoring='accuracy', cv=3, n_jobs=-1, random_state=42
)

# Perform the hyperparameter search
random_search.fit(X_train, y_train)

# Print the best hyperparameters found
print("Best Hyperparameters:", random_search.best_params_)

# Evaluate the best model on the test data
best_lr_model = random_search.best_estimator_
test_accuracy = best_lr_model.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy:.2f}")


Best Hyperparameters: {'solver': 'liblinear', 'penalty': 'l2', 'max_iter': 400, 'C': 0.07564633275546291}
Test Accuracy: 0.54
