In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [87]:
import seaborn as sns

ImportError: cannot import name 'ConciseDateFormatter' from 'matplotlib.dates' (C:\Users\GTDNL\anaconda3\envs\nlp_course\lib\site-packages\matplotlib\dates.py)

In [73]:
p = pd.read_csv('mycsvfile.csv')

In [74]:
p.head()

loan_amnt  term  sub_grade  emp_length  annual_inc  loan_status    dti  \
0     3600.0   1.0       24.0        10.0     55000.0          1.0   5.91   
1    20000.0   2.0       14.0        10.0     63000.0          1.0  10.78   
2    10400.0   2.0       51.0         3.0    104433.0          1.0  25.37   
3    20000.0   1.0       11.0        10.0     85000.0          1.0  17.61   
4    10000.0   1.0        2.0         6.0     85000.0          1.0  13.07   

   mths_since_recent_inq  revol_util  num_op_rev_tl  ...  addr_state__SD  \
0                    4.0        29.7            4.0  ...               0   
1                   10.0        56.2            4.0  ...               0   
2                    1.0        64.5            7.0  ...               0   
3                    8.0         5.7            3.0  ...               0   
4                    1.0        34.5           13.0  ...               0   

   addr_state__TN  addr_state__TX  addr_state__UT  addr_state__VA  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   addr_state__VT  addr_state__WA  addr_state__WI  addr_state__WV  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   addr_state__WY  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 66 columns]

In [86]:
sns.heatmap(p, annot=True, cmap='coolwarm')

NameError: name 'sns' is not defined

In [58]:
p.columns

Index(['loan_amnt', 'term', 'sub_grade', 'emp_length', 'annual_inc',
       'loan_status', 'dti', 'mths_since_recent_inq', 'revol_util',
       'num_op_rev_tl', 'home_ownership__ANY', 'home_ownership__MORTGAGE',
       'home_ownership__NONE', 'home_ownership__OTHER', 'home_ownership__OWN',
       'home_ownership__RENT', 'addr_state__AK', 'addr_state__AL',
       'addr_state__AR', 'addr_state__AZ', 'addr_state__CA', 'addr_state__CO',
       'addr_state__CT', 'addr_state__DC', 'addr_state__DE', 'addr_state__FL',
       'addr_state__GA', 'addr_state__HI', 'addr_state__ID', 'addr_state__IL',
       'addr_state__IN', 'addr_state__KS', 'addr_state__KY', 'addr_state__LA',
       'addr_state__MA', 'addr_state__MD', 'addr_state__ME', 'addr_state__MI',
       'addr_state__MN', 'addr_state__MO', 'addr_state__MS', 'addr_state__MT',
       'addr_state__NC', 'addr_state__ND', 'addr_state__NE', 'addr_state__NH',
       'addr_state__NJ', 'addr_state__NM', 'addr_state__NV', 'addr_state__NY',
       'ad

In [59]:
p['term'].value_counts()

1.0    620857
2.0    227597
Name: term, dtype: int64

In [60]:
p.tail()

loan_amnt  term  sub_grade  emp_length  annual_inc  loan_status  \
848449    22400.0   2.0       22.0        10.0    119000.0          0.0   
848450    19400.0   2.0       24.0         0.0     78000.0          1.0   
848451    11200.0   2.0       22.0         5.0     86000.0          0.0   
848452    23800.0   2.0       24.0        10.0    119000.0          1.0   
848453    24000.0   2.0       24.0         6.0    110000.0          0.0   

          dti  mths_since_recent_inq  revol_util  num_op_rev_tl  ...  \
848449  23.22                    1.0        51.5           12.0  ...   
848450  13.02                    2.0        63.8            9.0  ...   
848451   4.80                   10.0        54.7            7.0  ...   
848452  32.73                    0.0        89.5            8.0  ...   
848453  18.30                    9.0        68.1            8.0  ...   

        addr_state__SD  addr_state__TN  addr_state__TX  addr_state__UT  \
848449               0               0               0               0   
848450               0               0               0               0   
848451               0               0               0               0   
848452               0               0               0               0   
848453               0               0               0               0   

        addr_state__VA  addr_state__VT  addr_state__WA  addr_state__WI  \
848449               0               1               0               0   
848450               0               0               0               0   
848451               0               0               1               0   
848452               0               0               0               0   
848453               0               0               0               0   

        addr_state__WV  addr_state__WY  
848449               0               0  
848450               0               0  
848451               0               0  
848452               0               0  
848453               0               0  

[5 rows x 66 columns]

In [61]:
ro = p['loan_status']

In [62]:
ro.tail()

848449    0.0
848450    1.0
848451    0.0
848452    1.0
848453    0.0
Name: loan_status, dtype: float64

In [63]:
p.drop('loan_status',axis=1,inplace=True)

In [64]:
p.head()

loan_amnt  term  sub_grade  emp_length  annual_inc    dti  \
0     3600.0   1.0       24.0        10.0     55000.0   5.91   
1    20000.0   2.0       14.0        10.0     63000.0  10.78   
2    10400.0   2.0       51.0         3.0    104433.0  25.37   
3    20000.0   1.0       11.0        10.0     85000.0  17.61   
4    10000.0   1.0        2.0         6.0     85000.0  13.07   

   mths_since_recent_inq  revol_util  num_op_rev_tl  home_ownership__ANY  ...  \
0                    4.0        29.7            4.0                    0  ...   
1                   10.0        56.2            4.0                    0  ...   
2                    1.0        64.5            7.0                    0  ...   
3                    8.0         5.7            3.0                    0  ...   
4                    1.0        34.5           13.0                    0  ...   

   addr_state__SD  addr_state__TN  addr_state__TX  addr_state__UT  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   addr_state__VA  addr_state__VT  addr_state__WA  addr_state__WI  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   addr_state__WV  addr_state__WY  
0               0               0  
1               0               0  
2               0               0  
3               0               0  
4               0               0  

[5 rows x 65 columns]

In [65]:
X = p

In [66]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [67]:
X_train, X_test, ro_train, ro_test = train_test_split(X, ro, test_size=0.40, random_state=42)

In [39]:
from sklearn.preprocessing import StandardScaler
sd= StandardScaler()
X_train = sd.fit_transform(X_train)
X_test = sd.fit_transform(X_test)

In [68]:
ro_train.value_counts()

1.0    403598
0.0    105474
Name: loan_status, dtype: int64

In [69]:
ro_test.value_counts()

1.0    268779
0.0     70603
Name: loan_status, dtype: int64

In [23]:
from sklearn.feature_selection import mutual_info_regression,mutual_info_classif
mi=mutual_info_classif(X_train,ro_train)
mi=pd.Series(mi)
mi.index=X.columns
lol=mi.sort_values(ascending=False)
from sklearn.feature_selection import SelectPercentile
sel=SelectPercentile(mutual_info_classif,percentile=30).fit(X_train,ro_train)
X.columns[sel.get_support()]

Index(['loan_amnt', 'term', 'sub_grade', 'emp_length', 'annual_inc', 'dti',
       'mths_since_recent_inq', 'revol_util', 'num_op_rev_tl',
       'home_ownership__MORTGAGE', 'home_ownership__NONE',
       'home_ownership__RENT', 'addr_state__AZ', 'addr_state__CA',
       'addr_state__FL', 'addr_state__NE', 'addr_state__NY', 'addr_state__OR',
       'addr_state__SD', 'addr_state__TX'],
      dtype='object')

In [24]:
x = X[['loan_amnt', 'term', 'sub_grade', 'emp_length', 'annual_inc', 'dti',
       'mths_since_recent_inq', 'revol_util', 'num_op_rev_tl',
       'home_ownership__MORTGAGE', 'home_ownership__NONE',
       'home_ownership__RENT', 'addr_state__AZ', 'addr_state__CA',
       'addr_state__FL', 'addr_state__NE', 'addr_state__NY', 'addr_state__OR',
       'addr_state__SD', 'addr_state__TX']]

In [81]:
from imblearn.under_sampling import TomekLinks
from imblearn.over_sampling import SMOTE

In [82]:
sm = SMOTE(
    sampling_strategy='auto',  # samples only the minority class
    random_state=0,  # for reproducibility
    k_neighbors=5
)

X_sm, y_sm = sm.fit_resample(X, ro)

ERROR! Session/line number was not unique in database. History logging moved to new session 54


In [83]:
y_sm.value_counts()

1.0    672377
0.0    672377
Name: loan_status, dtype: int64

In [84]:
ro_train.value_counts()

1.0    403598
0.0    105474
Name: loan_status, dtype: int64

In [89]:
y_sm.tail(2)

1344752    0.0
1344753    0.0
Name: loan_status, dtype: float64

In [90]:
X_train, X_test, ro_train, ro_test = train_test_split(X_sm, y_sm, test_size=0.30, random_state=42)

In [26]:
from sklearn.metrics import accuracy_score

In [40]:
from sklearn.ensemble import RandomForestClassifier

In [95]:
sv=RandomForestClassifier(max_depth=26,n_estimators=300, min_samples_split=2, min_samples_leaf=5,bootstrap=True)

In [96]:
sv.fit(X_train,ro_train)

RandomForestClassifier(max_depth=26, min_samples_leaf=5, n_estimators=300)

In [97]:
rf2=sv.predict(X_test)
accuracy_score(rf2,ro_test)

0.8465273767001217

In [98]:
rf1=sv.predict(X_train)
accuracy_score(rf1,ro_train)

0.8701811379042564

In [99]:
ars = pd.concat([X_sm,y_sm],axis=1)

In [100]:
ars.to_csv('ars.csv')

In [104]:
X.tail()

loan_amnt  term  sub_grade  emp_length  annual_inc    dti  \
848449    22400.0   2.0       22.0        10.0    119000.0  23.22   
848450    19400.0   2.0       24.0         0.0     78000.0  13.02   
848451    11200.0   2.0       22.0         5.0     86000.0   4.80   
848452    23800.0   2.0       24.0        10.0    119000.0  32.73   
848453    24000.0   2.0       24.0         6.0    110000.0  18.30   

        mths_since_recent_inq  revol_util  num_op_rev_tl  home_ownership__ANY  \
848449                    1.0        51.5           12.0                    0   
848450                    2.0        63.8            9.0                    0   
848451                   10.0        54.7            7.0                    0   
848452                    0.0        89.5            8.0                    0   
848453                    9.0        68.1            8.0                    0   

        ...  addr_state__SD  addr_state__TN  addr_state__TX  addr_state__UT  \
848449  ...               0               0               0               0   
848450  ...               0               0               0               0   
848451  ...               0               0               0               0   
848452  ...               0               0               0               0   
848453  ...               0               0               0               0   

        addr_state__VA  addr_state__VT  addr_state__WA  addr_state__WI  \
848449               0               1               0               0   
848450               0               0               0               0   
848451               0               0               1               0   
848452               0               0               0               0   
848453               0               0               0               0   

        addr_state__WV  addr_state__WY  
848449               0               0  
848450               0               0  
848451               0               0  
848452               0               0  
848453               0               0  

[5 rows x 65 columns]

In [103]:
X_sm.tail()

loan_amnt      term  sub_grade  emp_length  annual_inc        dti  \
1344749  18500.000000  2.000000  15.393783   10.000000     60000.0  15.514145   
1344750  10000.000000  1.994472  32.005528    3.038695     94000.0  18.478292   
1344751  26410.562297  1.000000  18.914886    1.056230     82000.0  19.125936   
1344752   4937.025470  1.000000  21.166146    4.518981     89000.0  25.040983   
1344753  22500.000000  1.000000  28.047468    6.107199     50000.0  29.503334   

         mths_since_recent_inq  revol_util  num_op_rev_tl  \
1344749              18.483937   75.190362       7.478757   
1344750               1.000000   34.356882       7.055279   
1344751              11.155016   49.168689      13.267476   
1344752               5.110764   64.712818      22.518981   
1344753               9.369066   78.583465       6.892801   

         home_ownership__ANY  ...  addr_state__SD  addr_state__TN  \
1344749                    0  ...               0               0   
1344750                    0  ...               0               0   
1344751                    0  ...               0               0   
1344752                    0  ...               0               0   
1344753                    0  ...               0               0   

         addr_state__TX  addr_state__UT  addr_state__VA  addr_state__VT  \
1344749               0               0               0               0   
1344750               0               0               0               0   
1344751               0               0               0               0   
1344752               0               0               0               0   
1344753               0               0               0               0   

         addr_state__WA  addr_state__WI  addr_state__WV  addr_state__WY  
1344749               0               0               0               0  
1344750               0               0               0               0  
1344751               0               0               0               0  
1344752               0               0               0               0  
1344753               0               0               0               0  

[5 rows x 65 columns]

In [76]:
p = pd.read_csv('ars.csv')

In [77]:
p.describe()

Unnamed: 0     loan_amnt          term     sub_grade    emp_length  \
count  1.344754e+06  1.344754e+06  1.344754e+06  1.344754e+06  1.344754e+06   
mean   6.723765e+05  1.527977e+04  1.329998e+00  2.365404e+01  6.119751e+00   
std    3.881972e+05  8.360358e+03  4.486857e-01  1.273937e+01  3.469706e+00   
min    0.000000e+00  1.000000e+03  1.000000e+00  1.000000e+00  0.000000e+00   
25%    3.361882e+05  9.000000e+03  1.000000e+00  1.400000e+01  3.000000e+00   
50%    6.723765e+05  1.434374e+04  1.000000e+00  2.300000e+01  6.450512e+00   
75%    1.008565e+06  2.000000e+04  2.000000e+00  3.200000e+01  1.000000e+01   
max    1.344753e+06  4.000000e+04  2.000000e+00  6.500000e+01  1.000000e+01   

         annual_inc           dti  mths_since_recent_inq    revol_util  \
count  1.344754e+06  1.344754e+06           1.344754e+06  1.344754e+06   
mean   7.151406e+04  1.919664e+01           6.396686e+00  5.386607e+01   
std    2.531758e+04  7.903428e+00           5.448595e+00  2.254868e+01   
min    3.500099e+04 -1.000000e+00           0.000000e+00  0.000000e+00   
25%    5.000000e+04  1.341848e+01           2.000000e+00  3.750000e+01   
50%    6.551503e+04  1.893394e+01           5.000000e+00  5.432643e+01   
75%    8.700000e+04  2.484000e+01           9.073095e+00  7.092477e+01   
max    1.449990e+05  4.500000e+01           2.500000e+01  1.480000e+02   

       num_op_rev_tl  ...  addr_state__TN  addr_state__TX  addr_state__UT  \
count   1.344754e+06  ...    1.344754e+06    1.344754e+06    1.344754e+06   
mean    8.475898e+00  ...    1.008065e-02    5.706025e-02    4.732464e-03   
std     4.141467e+00  ...    9.989515e-02    2.319578e-01    6.862996e-02   
min     0.000000e+00  ...    0.000000e+00    0.000000e+00    0.000000e+00   
25%     5.591912e+00  ...    0.000000e+00    0.000000e+00    0.000000e+00   
50%     8.000000e+00  ...    0.000000e+00    0.000000e+00    0.000000e+00   
75%     1.078065e+01  ...    0.000000e+00    0.000000e+00    0.000000e+00   
max     3.500000e+01  ...    1.000000e+00    1.000000e+00    1.000000e+00   

       addr_state__VA  addr_state__VT  addr_state__WA  addr_state__WI  \
count    1.344754e+06    1.344754e+06    1.344754e+06    1.344754e+06   
mean     1.744780e-02    1.335560e-03    1.412005e-02    8.832842e-03   
std      1.309328e-01    3.652092e-02    1.179860e-01    9.356725e-02   
min      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
25%      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
50%      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
75%      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
max      1.000000e+00    1.000000e+00    1.000000e+00    1.000000e+00   

       addr_state__WV  addr_state__WY  loan_status  
count    1.344754e+06    1.344754e+06    1344754.0  
mean     2.216019e-03    1.483543e-03          0.5  
std      4.702244e-02    3.848822e-02          0.5  
min      0.000000e+00    0.000000e+00          0.0  
25%      0.000000e+00    0.000000e+00          0.0  
50%      0.000000e+00    0.000000e+00          0.5  
75%      0.000000e+00    0.000000e+00          1.0  
max      1.000000e+00    1.000000e+00          1.0  

[8 rows x 67 columns]

In [5]:
X = p.iloc[:,1:]

In [78]:
X.describe()

loan_amnt          term     sub_grade    emp_length    annual_inc  \
count  1.344754e+06  1.344754e+06  1.344754e+06  1.344754e+06  1.344754e+06   
mean   1.527977e+04  1.329998e+00  2.365404e+01  6.119751e+00  7.151406e+04   
std    8.360358e+03  4.486857e-01  1.273937e+01  3.469706e+00  2.531758e+04   
min    1.000000e+03  1.000000e+00  1.000000e+00  0.000000e+00  3.500099e+04   
25%    9.000000e+03  1.000000e+00  1.400000e+01  3.000000e+00  5.000000e+04   
50%    1.434374e+04  1.000000e+00  2.300000e+01  6.450512e+00  6.551503e+04   
75%    2.000000e+04  2.000000e+00  3.200000e+01  1.000000e+01  8.700000e+04   
max    4.000000e+04  2.000000e+00  6.500000e+01  1.000000e+01  1.449990e+05   

                dti  mths_since_recent_inq    revol_util  num_op_rev_tl  \
count  1.344754e+06           1.344754e+06  1.344754e+06   1.344754e+06   
mean   1.919664e+01           6.396686e+00  5.386607e+01   8.475898e+00   
std    7.903428e+00           5.448595e+00  2.254868e+01   4.141467e+00   
min   -1.000000e+00           0.000000e+00  0.000000e+00   0.000000e+00   
25%    1.341848e+01           2.000000e+00  3.750000e+01   5.591912e+00   
50%    1.893394e+01           5.000000e+00  5.432643e+01   8.000000e+00   
75%    2.484000e+01           9.073095e+00  7.092477e+01   1.078065e+01   
max    4.500000e+01           2.500000e+01  1.480000e+02   3.500000e+01   

       home_ownership__MORTGAGE  home_ownership__OWN  home_ownership__RENT  \
count              1.344754e+06         1.344754e+06          1.344754e+06   
mean               4.130473e-01         6.379011e-02          3.182366e-01   
std                4.923814e-01         2.443787e-01          4.657921e-01   
min                0.000000e+00         0.000000e+00          0.000000e+00   
25%                0.000000e+00         0.000000e+00          0.000000e+00   
50%                0.000000e+00         0.000000e+00          0.000000e+00   
75%                1.000000e+00         0.000000e+00          1.000000e+00   
max                1.000000e+00         1.000000e+00          1.000000e+00   

       addr_state__CA  addr_state__FL  addr_state__GA  addr_state__IL  \
count    1.344754e+06    1.344754e+06    1.344754e+06    1.344754e+06   
mean     9.603987e-02    4.527668e-02    2.068111e-02    2.637211e-02   
std      2.946460e-01    2.079104e-01    1.423145e-01    1.602393e-01   
min      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
25%      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
50%      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
75%      0.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00   
max      1.000000e+00    1.000000e+00    1.000000e+00    1.000000e+00   

       addr_state__NY  addr_state__OH  addr_state__TX  
count    1.344754e+06    1.344754e+06    1.344754e+06  
mean     5.178047e-02    2.178986e-02    5.706025e-02  
std      2.215836e-01    1.459968e-01    2.319578e-01  
min      0.000000e+00    0.000000e+00    0.000000e+00  
25%      0.000000e+00    0.000000e+00    0.000000e+00  
50%      0.000000e+00    0.000000e+00    0.000000e+00  
75%      0.000000e+00    0.000000e+00    0.000000e+00  
max      1.000000e+00    1.000000e+00    1.000000e+00

In [6]:
y = p.iloc[:,-1]

In [7]:
X = X[['loan_amnt', 'term', 'sub_grade', 'emp_length', 'annual_inc', 'dti',
       'mths_since_recent_inq', 'revol_util', 'num_op_rev_tl',
       'home_ownership__MORTGAGE', 'home_ownership__OWN',
       'home_ownership__RENT', 'addr_state__CA', 'addr_state__FL',
       'addr_state__GA', 'addr_state__IL', 'addr_state__NY', 'addr_state__OH',
       'addr_state__TX']]

In [8]:
y.head()

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: loan_status, dtype: float64

In [10]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.ensemble import RandomForestClassifier

In [14]:
from sklearn.metrics import accuracy_score, roc_auc_score,confusion_matrix

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=52)

In [19]:
sv=RandomForestClassifier(n_estimators=100, min_samples_split=5, min_samples_leaf=1, max_depth=None,bootstrap=False)

In [20]:
sv.fit(X_train,y_train)
rf1=sv.predict(X_train)
accuracy_score(rf1,y_train)

1.0

In [21]:
roc_auc_score(rf1,y_train)

1.0

In [22]:
confusion_matrix(rf1,y_train)

array([[470437,      0],
       [     0, 470890]], dtype=int64)

In [26]:
rf2=sv.predict(X_test)
accuracy_score(rf2,y_test)

0.8639976997077539

In [23]:
roc_auc_score(rf2,y_test)

0.8769369746980858

In [25]:
confusion_matrix(rf2,y_test)

array([[155606,   8610],
       [ 46334, 192877]], dtype=int64)

In [27]:
from sklearn.linear_model import LogisticRegression

In [42]:
model = LogisticRegression(solver='liblinear',penalty='l2',max_iter=400)

In [43]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=400, solver='liblinear')

In [44]:
r=model.predict(X_train)
accuracy_score(r,y_train)

0.7625001726286402

In [45]:
roc_auc_score(r,y_train)

0.7690147128445706

In [46]:
confusion_matrix(r,y_train)

array([[322041,  75169],
       [148396, 395721]], dtype=int64)

In [50]:
rf2=model.predict(X_test)
accuracy_score(rf2,y_test)

0.7633078599102192

In [51]:
roc_auc_score(rf2,y_test)

0.7697925649358615

In [52]:
confusion_matrix(rf2,y_test)

array([[138551,  32099],
       [ 63389, 169388]], dtype=int64)

In [53]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
dr = DecisionTreeClassifier(splitter='best', min_samples_split= 2, min_samples_leaf=1, max_features=None, max_depth= 35, 
                            criterion ='gini')

In [66]:
dr.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=35)

In [67]:
d=dr.predict(X_train)
accuracy_score(d,y_train)

0.9838292113155153

In [68]:
roc_auc_score(d,y_train)

0.983943740618988

In [69]:
confusion_matrix(d,y_train)

array([[459260,   4045],
       [ 11177, 466845]], dtype=int64)

In [70]:
rf2=dr.predict(X_test)
accuracy_score(rf2,y_test)

0.8032952677931819

In [71]:
roc_auc_score(rf2,y_test)

0.8032984123665878

In [72]:
confusion_matrix(rf2,y_test)

array([[162580,  39996],
       [ 39360, 161491]], dtype=int64)